name: Dallas Sofa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54983
title: Dallas Sofa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 1
  lightness: 0.991817022440955
  saturation: 0.25
  rhythmicContrast: 0.39581371704116464
purpose: []
